% /home/david/.isabelle/contrib/zipperposition-2.1-1/x86_64-linux/zipperposition --input tptp --output tptp --timeout 30.000 --mode=ho-pragmatic --tptp-def-as-rewrite --rewrite-before-cnf=true --max-inferences=1 --ho-unif-max-depth=1 --ho-max-elims=0 --ho-max-app-projections=0 --ho-max-rigid-imitations=1 --ho-max-identifications=0 --boolean-reasoning=bool-hoist --bool-hoist-simpl=true --bool-select=LI --recognize-injectivity=true --ext-rules=ext-family --ext-rules-max-depth=1 --ho-choice-inst=true --ho-prim-enum=none --ho-elim-leibniz=0 --interpret-bool-funs=true --try-e="$E_HOME/eprover" --tmp-dir="$ISABELLE_TMP_PREFIX" --ho-unif-level=pragmatic-framework --select=bb+e-selection2 --post-cnf-lambda-lifting=true -q "4|prefer-sos|pnrefined(2,1,1,1,2,2,2)" -q "6|prefer-processed|conjecture-relative-struct(1.5,3.5,2,3)" -q "1|const|fifo" -q "4|prefer-ground|orient-lmax(2,1,2,1,1)" -q "4|defer-sos|conjecture-relative-struct(1,5,2,3)" --avatar=off --recognize-injectivity=true --ho-neg-ext=true --e-timeout=2 --ho-pattern-decider=true --ho-fixpoint-decider=true --e-max-derived=50 --ignore-orphans=true --e-auto=true --presaturate=true --e-call-point=0.1 /home/david/.isabelle/prob_zipperposition_1.p
% This file was generated by Isabelle (most likely Sledgehammer)
% 2023-07-11 18:26:18.214

% Could-be-implicit typings (2)
thf(ty_n_t__List__Olist_Itf__a_J, type,
    list_a : $tType).
thf(ty_n_tf__a, type,
    a : $tType).

% Explicit typings (5)
thf(sy_c_List_Oappend_001tf__a, type,
    append_a : list_a > list_a > list_a).
thf(sy_c_List_Olist_OCons_001tf__a, type,
    cons_a : a > list_a > list_a).
thf(sy_c_List_Olist_ONil_001tf__a, type,
    nil_a : list_a).
thf(sy_c_List_Orev_001tf__a, type,
    rev_a : list_a > list_a).
thf(sy_v_a, type,
    a2 : a).

% Relevant facts (4)
thf(fact_0_append__Cons, axiom,
    ((![X : a, Xs : list_a, Ys : list_a]: ((append_a @ (cons_a @ X @ Xs) @ Ys) = (cons_a @ X @ (append_a @ Xs @ Ys))))), [], [isabelle_rec_def, isabelle_rank(900)]). % append_Cons
thf(fact_1_rev_Osimps_I1_J, axiom,
    (((rev_a @ nil_a) = nil_a)), [], [isabelle_non_rec_def, isabelle_rank(1575)]). % rev.simps(1)
thf(fact_2_rev_Osimps_I2_J, axiom,
    ((![X : a, Xs : list_a]: ((rev_a @ (cons_a @ X @ Xs)) = (append_a @ (rev_a @ Xs) @ (cons_a @ X @ nil_a))))), [], [isabelle_rec_def, isabelle_rank(2250)]). % rev.simps(2)
thf(fact_3_rev__singleton__conv, axiom,
    ((![Xs : list_a, X : a]: (((rev_a @ Xs) = (cons_a @ X @ nil_a)) = (Xs = (cons_a @ X @ nil_a))))), [], [isabelle_simp, isabelle_rank(2925)]). % rev_singleton_conv

% Conjectures (1)
thf(conj_0, conjecture,
    (((rev_a @ (cons_a @ a2 @ nil_a)) = (cons_a @ a2 @ nil_a)))).
